api_config:
  authentication: configured_via_secrets
  endpoints: &id001
  - chat.openai.com
entity:
  api_endpoints: *id001
  capabilities:
  - chatgpt_api
  - conversation
  - code_assistance
  classification: Internal Secret - CoolBits.ai Members Only
  integration_status: active
  name: ChatGPT
  provider: OpenAI
  role: ChatGPT Integration
integration:
  cbLM_integration: true
  last_updated: '2025-09-07T07:15:25.571407'
  status: active
policy:
  classification: Internal Secret - CoolBits.ai Members Only
  policy_division:
    caio: oGrok09
    ciso: oGrok08
    policy_systems:
    - coolbits.ai/policy
    - coolbits.ai/policy-manager
    - cblm.ai/policy
    - cblm.ai/policy-manager
