api_config:
  authentication: configured_via_secrets
  endpoints: &id001
  - microsoft.com
  - azure.microsoft.com
entity:
  api_endpoints: *id001
  capabilities:
  - windows_11
  - copilot
  - azure_integration
  classification: Internal Secret - CoolBits.ai Members Only
  integration_status: active
  name: Microsoft Ecosystem
  provider: Microsoft
  role: Windows 11 + Microsoft Ecosystem
integration:
  cbLM_integration: true
  last_updated: '2025-09-07T07:15:25.559551'
  status: active
policy:
  classification: Internal Secret - CoolBits.ai Members Only
  policy_division:
    caio: oGrok09
    ciso: oGrok08
    policy_systems:
    - coolbits.ai/policy
    - coolbits.ai/policy-manager
    - cblm.ai/policy
    - cblm.ai/policy-manager
