version: "3.9"
services:
  web:
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: ["gpu"]
    environment:
      NVIDIA_VISIBLE_DEVICES: "all"
      NVIDIA_DRIVER_CAPABILITIES: "compute,utility"
