version: "3.8"
services:
  web:
    image: ghcr.io/coolbits-dm/coolbits.ai:latest
    container_name: coolbits_web_prod
    restart: unless-stopped
    env_file: .env
    environment:
      OPIPE_ENV: ${OPIPE_ENV:-prod}
      DB_URL: ${DB_URL:-sqlite:///./data/coolbits.db}
      AGENTS_ENABLED: ${AGENTS_ENABLED:-mock}
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD-SHELL","curl -fsS http://localhost:8501/_stcore/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G

  qdrant:
    image: qdrant/qdrant:latest
    container_name: coolbits_qdrant_prod
    restart: unless-stopped
    volumes:
      - ./qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"
    healthcheck:
      test: ["CMD","wget","-q","-O-","http://localhost:6333/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
