# Google Cloud Organization Setup for COOL BITS SRL
# Generated by @oGit Agent for coolbits.ai V1.2

# 1. Set project and organization
gcloud config set project coolbits-ai
gcloud config set compute/region europe-west1
gcloud config set compute/zone europe-west1-b

# 2. Enable required APIs
gcloud services enable aiplatform.googleapis.com compute.googleapis.com storage.googleapis.com secretmanager.googleapis.com bigquery.googleapis.com datastore.googleapis.com ml.googleapis.com cloudbuild.googleapis.com container.googleapis.com run.googleapis.com

# 3. Create service accounts
# Create CoolBits AI Admin Service Account
gcloud iam service-accounts create coolbits-ai-admin \
    --display-name="CoolBits AI Admin Service Account" \
    --description="Administrative access for CoolBits.ai platform"

# Assign roles to coolbits-ai-admin
gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-admin@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/owner"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-admin@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/iam.serviceAccountAdmin"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-admin@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/resourcemanager.projectIamAdmin"

# Create CoolBits AI Vertex Service Account
gcloud iam service-accounts create coolbits-ai-vertex \
    --display-name="CoolBits AI Vertex Service Account" \
    --description="Vertex AI access for AI model training and inference"

# Assign roles to coolbits-ai-vertex
gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-vertex@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/aiplatform.user"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-vertex@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/ml.developer"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-vertex@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/storage.admin"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-vertex@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/bigquery.dataEditor"

# Create CoolBits AI CUDA Service Account
gcloud iam service-accounts create coolbits-ai-cuda \
    --display-name="CoolBits AI CUDA Service Account" \
    --description="CUDA-enabled GPU access for AI processing"

# Assign roles to coolbits-ai-cuda
gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-cuda@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/compute.instanceAdmin"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-cuda@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/compute.instanceAdmin.v1"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-cuda@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/aiplatform.user"

# Create CoolBits AI OpenAI Service Account
gcloud iam service-accounts create coolbits-ai-openai \
    --display-name="CoolBits AI OpenAI Service Account" \
    --description="OpenAI API integration service account"

# Assign roles to coolbits-ai-openai
gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-openai@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/secretmanager.secretAccessor"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-openai@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/aiplatform.user"

# Create CoolBits AI RAG Service Account
gcloud iam service-accounts create coolbits-ai-rag \
    --display-name="CoolBits AI RAG Service Account" \
    --description="RAG system and vector database access"

# Assign roles to coolbits-ai-rag
gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-rag@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/aiplatform.user"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-rag@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/storage.admin"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-rag@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/datastore.user"

gcloud projects add-iam-policy-binding coolbits-ai \
    --member="serviceAccount:coolbits-ai-rag@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/bigquery.dataEditor"

# 4. CUDA and GPU Configuration
# Enable GPU quota for CUDA processing
gcloud compute project-info add-metadata \
    --metadata=gpu-quota=true

# Create GPU-enabled instance template
gcloud compute instance-templates create coolbits-gpu-template \
    --machine-type=n1-standard-4 \
    --accelerator=type=nvidia-tesla-t4,count=1 \
    --image-family=tf-latest-gpu \
    --image-project=deeplearning-platform-release \
    --boot-disk-size=100GB \
    --boot-disk-type=pd-ssd

# 5. Vertex AI Configuration
# Create Vertex AI dataset
gcloud ai datasets create \
    --display-name="CoolBits AI Training Data" \
    --metadata-schema-uri="gs://google-cloud-aiplatform/schema/dataset/metadata/text_1.0.0.yaml"

# Create Vertex AI model endpoint
gcloud ai endpoints create \
    --display-name="CoolBits AI Model Endpoint" \
    --region=europe-west1

# 6. Security Configuration
# Create secrets for API keys
gcloud secrets create openai-api-key \
    --data-file=- <<< "YOUR_OPENAI_API_KEY"

gcloud secrets create xai-api-key \
    --data-file=- <<< "YOUR_XAI_API_KEY"

# Grant access to secrets
gcloud secrets add-iam-policy-binding openai-api-key \
    --member="serviceAccount:coolbits-ai-openai@coolbits-ai.iam.gserviceaccount.com" \
    --role="roles/secretmanager.secretAccessor"

# 7. Storage Configuration
# Create storage buckets
gsutil mb gs://coolbits-ai-ai-models
gsutil mb gs://coolbits-ai-training-data
gsutil mb gs://coolbits-ai-rag-vectors

# 8. Monitoring and Logging
# Enable monitoring
gcloud services enable monitoring.googleapis.com
gcloud services enable logging.googleapis.com

# Create monitoring dashboard
gcloud monitoring dashboards create \
    --config-from-file=coolbits-monitoring-dashboard.json

# 9. Network Configuration
# Create VPC for AI workloads
gcloud compute networks create coolbits-ai-vpc \
    --subnet-mode=regional \
    --bgp-routing-mode=global

gcloud compute networks subnets create coolbits-ai-subnet \
    --network=coolbits-ai-vpc \
    --range=10.0.0.0/24 \
    --region=europe-west1

# 10. Final Configuration
# Set default network tags
gcloud config set compute/network coolbits-ai-vpc
gcloud config set compute/subnet coolbits-ai-subnet

# Display configuration summary
echo "Google Cloud Organization Setup Complete for COOL BITS SRL"
echo "Project ID: coolbits-ai"
echo "Organization: COOL BITS SRL"
echo "CEO: andrei@coolbits.ro"
echo "CUDA Support: Enabled"
echo "GPU: NVIDIA RTX 2060"
echo "Certificate Manager: @oSafeNet"
echo "SmartBill Manager: @oSmartBill"