api_config:
  authentication: configured_via_secrets
  endpoints: &id001
  - grok.x.ai
entity:
  api_endpoints: *id001
  capabilities:
  - grok_api
  - real_time
  - reasoning
  classification: Internal Secret - CoolBits.ai Members Only
  integration_status: active
  name: Grok AI
  provider: xAI
  role: Grok API Integration
integration:
  cbLM_integration: true
  last_updated: '2025-09-07T07:15:25.563996'
  status: active
policy:
  classification: Internal Secret - CoolBits.ai Members Only
  policy_division:
    caio: oGrok09
    ciso: oGrok08
    policy_systems:
    - coolbits.ai/policy
    - coolbits.ai/policy-manager
    - cblm.ai/policy
    - cblm.ai/policy-manager
