api_config:
  authentication: configured_via_secrets
  endpoints: &id001
  - api.openai.com
entity:
  api_endpoints: *id001
  capabilities:
  - gpt_models
  - api_access
  - codex
  classification: Internal Secret - CoolBits.ai Members Only
  integration_status: active
  name: OpenAI Platform
  provider: OpenAI
  role: OpenAI Platform Integration
integration:
  cbLM_integration: true
  last_updated: '2025-09-07T07:15:25.569071'
  status: active
policy:
  classification: Internal Secret - CoolBits.ai Members Only
  policy_division:
    caio: oGrok09
    ciso: oGrok08
    policy_systems:
    - coolbits.ai/policy
    - coolbits.ai/policy-manager
    - cblm.ai/policy
    - cblm.ai/policy-manager
