api_config:
  authentication: configured_via_secrets
  endpoints: &id001
  - cursor.sh
entity:
  api_endpoints: *id001
  capabilities:
  - code_generation
  - development_tools
  - microsoft_ecosystem
  classification: Internal Secret - CoolBits.ai Members Only
  integration_status: active
  name: Cursor AI Assistant
  provider: Cursor
  role: Development Environment Coordinator
integration:
  cbLM_integration: true
  last_updated: '2025-09-07T07:15:25.554841'
  status: active
policy:
  classification: Internal Secret - CoolBits.ai Members Only
  policy_division:
    caio: oGrok09
    ciso: oGrok08
    policy_systems:
    - coolbits.ai/policy
    - coolbits.ai/policy-manager
    - cblm.ai/policy
    - cblm.ai/policy-manager
