# CoolBits.ai NHA Registry - JSONSchema Validation
# Schema for validating agents.yaml structure

type: object
required: [version, nhas]
properties:
  version: 
    type: string
    pattern: "^[0-9]+\\.[0-9]+\\.[0-9]+$"
  nhas:
    type: array
    minItems: 1
    items:
      type: object
      required: [id, name, category, owner, channels]
      properties:
        id: 
          type: string
          pattern: "^nha:[a-z0-9\\-]+$"
        name: 
          type: string
          minLength: 1
        category: 
          enum: ["personal", "biz_channels", "biz_tools", "seo_tools", "agency", "dev_tools", "infra", "security", "mlops", "ops"]
        owner: 
          type: string
          minLength: 1
        status: 
          enum: ["active", "paused", "deprecated"]
          default: "active"
        channels:
          type: array
          minItems: 1
          items:
            type: object
            required: [kind, endpoint]
            properties:
              kind: 
                enum: ["http", "ws", "cli", "sdk", "ui"]
              endpoint: 
                type: string
                minLength: 1
              auth: 
                enum: ["none", "hmac", "jwt", "oauth", "sa_key", "kms"]
                default: "none"
        capabilities:
          type: array
          items: 
            type: object
            required: [name]
            properties:
              name:
                type: string
                minLength: 1
              description:
                type: string
                minLength: 1
              scopes:
                type: array
                items: 
                  type: string
                  pattern: "^[a-z]+:[a-z_]+$"
        permissions: 
          type: array
          items: 
            type: string
        secrets: 
          type: array
          items: 
            type: string
            pattern: "^nha/[a-z0-9\\-]+/[a-z_]+$"
        tags: 
          type: array
          items: 
            type: string
            pattern: "^[a-z]+:[a-z0-9\\-_]+$"
        slo:
          type: object
          properties:
            latency_p95_ms: 
              type: integer
              minimum: 1
              maximum: 1000000
            error_rate_max: 
              type: number
              minimum: 0.0
              maximum: 1.0
            availability_pct: 
              type: number
              minimum: 0.0
              maximum: 100.0
        notes: 
          type: string
