name: CI Verify (manual)
on: { workflow_dispatch: {} }

permissions: { contents: read }

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: '20' }
      - uses: actions/setup-python@v5
        with: { python-version: '3.11' }

      - name: Lint workflows (actionlint)
        run: |
          curl -sSL https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash \
            | bash -s -- -b ./.bin
          echo "./.bin" >> $GITHUB_PATH
          actionlint || true

      - name: Python deps
        run: |
          python -m pip install -U pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else echo "no reqs"; fi

      - name: Tests
        run: pytest -q || echo "pytest soft-fail in dev"
