name: CI/CD Pipeline
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
defaults:
  run:
    shell: bash

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'panel/**'
      - 'artifacts/**'
      - 'report/**'
      - '**/*.md'
      - '**/*.MD'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'panel/**'
      - 'artifacts/**'
      - 'report/**'
      - '**/*.md'
      - '**/*.MD'

env:
  CB_BILLING_MODE: dev

jobs:
  verify:
    if: ${{ github.event_name == 'pull_request' || env.CB_BILLING_MODE != 'prod' }}
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Node setup
        uses: actions/setup-node@v4
        with: { node-version: 20 }
      - run: npm ci || true
      - run: npm run lint --if-present || true
      - run: npm test --if-present || true

      - name: Python setup
        uses: actions/setup-python@v5
        with: { python-version: '3.11' }
      - run: python -m pip install -U pip ruff
      - run: ruff check . --fix && ruff format .

      - name: Actionlint
        uses: reviewdog/action-actionlint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-check
          level: error

  release:
    if: ${{ github.event_name == 'push' && env.CB_BILLING_MODE == 'prod' }}
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Billing guard
        run: bash scripts/billing_guard.sh