name: Build and Push Docker Image

on:
  push:
    tags: ['v*']
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata
        uses: docker/metadata-action@v5
        id: meta
        with:
          images: ghcr.io/coolbits-dm/coolbits.ai
          tags: |
            type=ref,event=tag
            type=raw,value=latest
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Generate SBOM
        uses: anchore/syft-action@v0
        with:
          image: ghcr.io/coolbits-dm/coolbits.ai:latest
          format: spdx-json
          output: artifacts/sbom.spdx.json
      
      - name: Security scan
        uses: aquasecurity/trivy-action@0.24.0
        with:
          image-ref: ghcr.io/coolbits-dm/coolbits.ai:latest
          format: 'table'
          vuln-type: 'os,library'
          output: artifacts/trivy-report.txt
      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: artifacts/
